site_name: hdsemg-shared
repo_name: hdsemg-shared
repo_url: https://github.com/johanneskasser/hdsemg-shared
site_url: https://johanneskasser.github.io/hdsemg-shared/
site_description: 'A Python library toolbox to work with high-density surface electromyography (HDsEMG) data.'
site_author: 'Johannes Kasser'

theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  color_mode: dark
  user_color_mode_toggle: true

nav:
  - Home: index.md
  - Installation:
      - Conda: installation/conda.md
      - Pip: installation/pip.md
  - Usage Documentation:
      - fileio: usage/fileio.md
      - filters: usage/filters.md
      - preprocessing: usage/preprocessing.md
      - grid: usage/grid.md
  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [src]  # search packages in the src folder