"""
Regression against real MATLAB output from SP_AM_CV_HDsEMG_Analysis.m.

Fixtures were generated by Global-HDsEMG-Analysis/test2py/globalAmplitude/
generate_fixtures.m: 12 channels on a 3-column x 4-row grid, fs 2048 Hz,
band-pass N=2 30-450 Hz, lowpass N=2 fc 6 Hz. The 'badch' case has channels
4 and 7 (base-0) set to NaN on the raw signal before any processing.
"""

import json
from pathlib import Path

import numpy as np
import pytest

from hdsemg_shared.filters.bandpass import bandpass_filter
from hdsemg_shared.global_parameters.global_amplitude import global_amplitude
from hdsemg_shared.preprocessing.grid_map import emg_map_from_indices, map_to_columns

ROOT = Path(__file__).parent
DATA = ROOT / "data" / "global_amplitude"

# Every MATLAB setting except the root ordering, reachable through the arguments
MATLAB_BPF = {"N": 2, "fcl": 30.0, "fch": 450.0, "corners": "prewarp"}
MATLAB_SMOOTH = {"mode": "lowpass", "fc": 6.0, "N": 2}


def _params():
    if not (DATA / "params.json").exists():
        pytest.skip(f"MATLAB fixtures not present at {DATA}")
    return json.loads((DATA / "params.json").read_text())


def _load(case, name):
    return np.loadtxt(DATA / case / name, delimiter=",")


def _emg_map(params):
    n_cols, n_rows = params["gridShape_nCols_nRows"]
    return emg_map_from_indices(range(params["nChannels"]), rows=n_rows, cols=n_cols)


def _steady(signal):
    return signal[len(signal) // 4:3 * len(signal) // 4]


@pytest.mark.parametrize("case", ["clean", "badch"])
def test_bandpass_prewarp_reproduces_matlab(case):
    # MATLAB band-passes the CLEAN raw and NaN-masks afterwards, so a bad
    # channel never reaches filtfilt -- reproduce that order here.
    params = _params()
    clean = _load("clean", "input_raw_mp.csv")

    got = bandpass_filter(clean, params["bpf"]["N"], params["bpf"]["fcl"], params["bpf"]["fch"],
                          params["fs"])
    if case == "badch":
        got[params["badChannels_0based_python"]] = np.nan

    np.testing.assert_allclose(got, _load(case, "bandpass_filtered_mp.csv"),
                               atol=1e-12, equal_nan=True)


@pytest.mark.parametrize("case", ["clean", "badch"])
@pytest.mark.parametrize("name,order", [("sd_grid.csv", 1), ("dd_grid.csv", 2)])
def test_derivation_reproduces_the_matlab_grids(case, name, order):
    # The driver feeds toDifferential's UNFILTERED output to globEMGAmpEnv,
    # so the SD/DD grids are pure algebraic differences of the raw signal --
    # which is exactly what global_amplitude does before it filters.
    params = _params()
    raw = _load(case, "input_raw_mp.csv")

    columns = map_to_columns(raw, _emg_map(params))
    got = np.vstack([np.diff(col, n=order, axis=0) for col in columns])

    np.testing.assert_allclose(got, _load(case, name), atol=1e-12, equal_nan=True)


@pytest.mark.parametrize("case", ["clean", "badch"])
@pytest.mark.parametrize("derivation,kept", [("MP", (12, 10)), ("SD", (9, 7)), ("DD", (6, 4))])
def test_nan_channels_are_dropped_the_way_matlab_ignores_them(case, derivation, kept):
    params = _params()
    raw = _load(case, "input_raw_mp.csv")

    out = global_amplitude(raw, _emg_map(params), params["fs"], derivation=derivation,
                           bpf=MATLAB_BPF, smooth=MATLAB_SMOOTH, pad_s=0.0)

    assert out.n_channels == (kept[0] if case == "clean" else kept[1])


@pytest.mark.parametrize("case", ["clean", "badch"])
@pytest.mark.parametrize("derivation,key", [("MP", "mp"), ("SD", "sd"), ("DD", "dd")])
def test_envelope_differs_from_matlab_only_by_the_root_ordering(case, derivation, key):
    # These fixtures are NOT expected to match: MATLAB reduces across the
    # channels at every sample and smooths afterwards, this implementation
    # smooths first and roots last. Every other setting is pinned to MATLAB's
    # above, so the ordering is the only difference left.
    #
    # No numeric prediction is asserted for the size of the gap. The
    # E[chi_n]/sqrt(n) factor assumes iid Gaussian channels, and these
    # fixtures are twelve deterministic sines at 40 + 10*(i-1) Hz plus a
    # little noise -- the cross-channel mean square of those is not
    # chi-distributed. That claim is tested on white noise instead, in
    # test_global_amplitude.py::test_amplitude_does_not_depend_on_how_many_channels_survived.
    params = _params()
    raw = _load(case, "input_raw_mp.csv")

    out = global_amplitude(raw, _emg_map(params), params["fs"], derivation=derivation,
                           bpf=MATLAB_BPF, smooth=MATLAB_SMOOTH, pad_s=0.0)
    matlab = _load(case, f"envelope_{key}_rms.csv")

    assert out.amplitude.shape == matlab.shape

    # Weighting by the channels' own energy, as the definition does, can only
    # raise the result relative to averaging per-channel roots.
    ratio = _steady(out.amplitude).mean() / _steady(matlab).mean()
    assert 1.0 <= ratio <= 1.3

    # The SD/DD envelopes vary over time, so shape agreement is meaningful
    # there and shows the chain up to the reduction is right. The MP envelope
    # of twelve constant-amplitude sines is nearly flat, so its correlation
    # carries no information and is not checked.
    if derivation in ("SD", "DD"):
        assert np.corrcoef(_steady(out.amplitude), _steady(matlab))[0, 1] > 0.99


@pytest.mark.parametrize("case", ["clean", "badch"])
def test_arv_envelope_also_tracks_the_matlab_shape(case):
    params = _params()
    raw = _load(case, "input_raw_mp.csv")

    out = global_amplitude(raw, _emg_map(params), params["fs"], method="ARV", derivation="SD",
                           bpf=MATLAB_BPF, smooth=MATLAB_SMOOTH, pad_s=0.0)
    matlab = _load(case, "envelope_sd_arv.csv")

    # ARV takes no root at all, so this branch matches MATLAB's reduction
    # order exactly -- mean of |x| commutes with the lowpass.
    np.testing.assert_allclose(_steady(out.amplitude), _steady(matlab), rtol=1e-9)
