name: 📦 Build & Deploy Docs

on:
  push:
    paths:
      - 'docs/**'  # Only trigger on changes in the docs directory
      - 'mkdocs.yml'  # Trigger on changes to the MkDocs configuration file
      - '.github/workflows/deploy-docs.yml'  # Trigger on changes to this workflow file
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing to gh-pages
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.x'  # Use the latest 3.10.x version

    - name: Install dependencies
      run: |
        pip install mkdocs mkdocs-material

    - name: Build the docs
      run: mkdocs build --strict

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
      with:
        publish_branch: gh-pages
        publish_dir: ./site
        keep_history: true

